name: Track Changed Files

on:
  push:
    branches:
      - master

jobs:
  track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # нужно для diff

      - name: Get initial commit
        id: get_initial
        run: echo "initial_commit=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_OUTPUT

      - name: Generate changes.txt
        run: |
          git diff --name-only ${{ steps.get_initial.outputs.initial_commit }}..HEAD > changes.txt
          cat changes.txt

      - name: Commit changes.txt to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Track changes: auto-update changes.txt"
          file_pattern: changes.txt
